# Generated by Django 5.1.1 on 2024-09-17 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comuna', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_region', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=9)),
                ('tipo_usuario', models.CharField(choices=[('Arrendador', 'Arrendador'), ('Arrendatario', 'Arrendatario')], default='Arrendador')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=200)),
                ('disponible', models.BooleanField(default=True)),
                ('m2_construidos', models.IntegerField()),
                ('m2_terreno', models.IntegerField()),
                ('cant_estacionamiento', models.IntegerField()),
                ('cant_banos', models.IntegerField()),
                ('cant_habitaciones', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('tipo_inmueble', models.CharField(choices=[('C', 'Casa'), ('D', 'Departamento'), ('P', 'Parcela')], default='D')),
                ('precio_arriendo', models.IntegerField()),
                ('arrendador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inmueble', to=settings.AUTH_USER_MODEL)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inmueble', to='m7_python.comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueble', to='m7_python.region')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('R', 'Rechazada'), ('A', 'Aprobada')], default='P')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='status', to=settings.AUTH_USER_MODEL)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='status', to='m7_python.inmueble')),
            ],
        ),
    ]
