# Generated by Django 5.1.1 on 2024-09-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_usuario',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
