# Generated by Django 5.1.1 on 2024-09-18 01:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0002_alter_detalle_usuario_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='region',
        ),
        migrations.RemoveField(
            model_name='region',
            name='id',
        ),
        migrations.AlterField(
            model_name='comuna',
            name='id_comuna',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detalle_usuario',
            name='rut',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='detalle_usuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='cant_banos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='cant_habitaciones',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='id_inmueble',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='m2_construidos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='m2_terreno',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='nombre',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio_arriendo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='region',
            name='id_region',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
