# Generated by Django 5.1.1 on 2024-09-18 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0003_remove_comuna_id_remove_inmueble_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='comunas', to='m7_python.region'),
        ),
    ]
