# Generated by Django 5.1.1 on 2024-09-18 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0005_alter_comuna_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inmuebles', to='m7_python.comuna'),
        ),
    ]
