# Generated by Django 5.1.1 on 2024-09-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0007_alter_inmueble_arrendador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='id_inmueble',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
