# Generated by Django 5.1.1 on 2024-09-20 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0009_inmueble_is_active_alter_inmueble_id_inmueble'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='id_comuna',
            new_name='cod',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='id_region',
            new_name='cod',
        ),
    ]
