# Generated by Django 5.1.1 on 2024-09-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0010_rename_id_comuna_comuna_cod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_usuario',
            name='telefono',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
