# Generated by Django 5.1.1 on 2024-09-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0011_alter_detalle_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='cod',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='cod',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
