# Generated by Django 5.1.1 on 2024-09-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0012_alter_comuna_cod_alter_region_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Arrendador', 'Arrendador'), ('Arrendatario', 'Arrendatario')], default='Arrendador', max_length=30),
        ),
    ]
